### PR TITLE
Fix Kubernetes 1.24 CI failed

### PR DESCRIPTION
**Pull request by jenting**
Signed-off-by: JenTing Hsiao <hsiaoairplane@gmail.com>

### CODE REVIEW

**Review by innobead — APPROVED** [review]

**Comment by kashifest** [comment]
@jenting @innobead Can we have a new release now since these changes are only in master?

**Comment by jenting** [comment]
> @jenting @innobead Can we have a new release now since these changes are only in master?

I've no permission to access this repo, but if you like, you could use this one
https://github.com/jenting/kucero/releases/tag/v1.6.1

**Comment by kashifest** [comment]
> > @jenting @innobead Can we have a new release now since these changes are only in master?
> 
> I've no permission to access this repo, but if you like, you could use this one https://github.com/jenting/kucero/releases/tag/v1.6.1

Ow, thanks!!! It would be still nice to have it from the upstream, any idea whom should I tag to ask for a release?

**Comment by jenting** [comment]
I think only @innobead has the permission now.

**Comment by kashifest** [comment]
> I think only @innobead has the permission now.

@innobead Do you have any plan for the next release?

**Pull request merged**
